 # Chapter 57 — Document Chunking: Breaking a PDF into Retrievable Pieces

Project
In this chapter, you will take a real PDF file, extract its text page by page, and split that text into smaller overlapping chunks. Each chunk keeps its source filename, page number, chunk ID, and word positions so a future retrieval system can point back to the source.

We will use the illustrative five-page Transaction Monitoring Alert Case Summary PDF from the earlier PDF-processing work. The information in that PDF is synthetic and for learning only.
Learning outcomes
By the end, you will be able to:
- extract selectable text from a PDF page by page;
- inspect page-level extraction quality before chunking;
- implement a configurable word-based chunker with overlap;
- preserve page-level provenance in every chunk;
- validate chunk size, overlap, IDs, and source metadata;
- export the resulting chunks to JSONL and CSV.

# Install the dependency

In [1]:
%pip install -q pypdf pandas

WARNING: You are using pip version 21.2.4; however, version 26.0.1 is available.
You should consider upgrading via the '/Library/Developer/CommandLineTools/usr/bin/python3 -m pip install --upgrade pip' command.
Note: you may need to restart the kernel to use updated packages.

# 2 Import Libraries

In [2]:
from pathlib import Path
import hashlib
import json
import re
import pandas as pd
from pypdf import PdfReader

# 3. Locate the PDF you downloaded

In [3]:
PDF_NAME = "Chapter 57 - Alert_Case_Summary.pdf"
PDF_PATH = Path(PDF_NAME)

In [4]:
if not PDF_PATH.is_file():
    pdf_candidates = sorted(Path.cwd().glob("*.pdf"))
    if len(pdf_candidates) == 1:
        PDF_PATH = pdf_candidates[0]
        print(f"expected file name not found")
    elif len(pdf_candidates) == 0:
        raise FileNotFoundError("File not found, update pdf path")

    else: 
        raise FileNotFoundError("More than one pdf was found")

 PDF_PATH: A pathlib.Path object pointing to the target PDF file.

 .read_bytes(): Opens the file in binary mode ("rb"), reads its entire content into memory as raw bytes (bytes object), and automatically closes the file.

 pdf_bytes: Holds the binary data of the PDF.

In [5]:
pdf_bytes = PDF_PATH.read_bytes()

In [6]:
pdf_bytes

b'%PDF-1.4\n%\x93\x8c\x8b\x9e ReportLab Generated PDF document (opensource)\n1 0 obj\n<<\n/F1 2 0 R /F2 3 0 R\n>>\nendobj\n2 0 obj\n<<\n/BaseFont /Helvetica /Encoding /WinAnsiEncoding /Name /F1 /Subtype /Type1 /Type /Font\n>>\nendobj\n3 0 obj\n<<\n/BaseFont /Helvetica-Bold /Encoding /WinAnsiEncoding /Name /F2 /Subtype /Type1 /Type /Font\n>>\nendobj\n4 0 obj\n<<\n/Contents 20 0 R /MediaBox [ 0 0 595.2756 841.8898 ] /Parent 19 0 R /Resources <<\n/Font 1 0 R /ProcSet [ /PDF /Text /ImageB /ImageC /ImageI ]\n>> /Rotate 0 /Trans <<\n\n>> \n  /Type /Page\n>>\nendobj\n5 0 obj\n<<\n/Contents 21 0 R /MediaBox [ 0 0 595.2756 841.8898 ] /Parent 19 0 R /Resources <<\n/Font 1 0 R /ProcSet [ /PDF /Text /ImageB /ImageC /ImageI ]\n>> /Rotate 0 /Trans <<\n\n>> \n  /Type /Page\n>>\nendobj\n6 0 obj\n<<\n/BitsPerComponent 8 /ColorSpace /DeviceRGB /Filter [ /ASCII85Decode /FlateDecode ] /Height 415 /Length 31510 /SMask 7 0 R \n  /Subtype /Image /Type /XObject /Width 1146\n>>\nstream\nGb",k$(+]2q=SB1(hR/X"qYa<SH7CX&-ZT#U4OSI-n6j"U(L3kfj-j2e0IKti^*bnC/?"3&ATm#0nL=1\\E"/MM[537/:sN=bC"6*`qs&RH\\NsdmO@!R^ZR^Ah::&bDqB>39c\\-Gm=GC+#U+j463n`f&4-XGKFgHU+bUCn#U+j463n`f&4-XGKFgHU+bUCn#U+j463n`f&4-XGKFgHU+bUCn#U+j463n`f&4-XGKFgHU+bUCn#U+j463n`f&4-XGKFgHU+bUCn#U+j463n`f&4-XGKFgHU+bUCn#U+j463n`f&4-XGKFgHU+bUCn#U+j463n`f&4-XG;=hp\\Y9Xj\'M#&2;*8(dF\\E&fGA2N@SoSspbnB`A4&4-YBNQIA3-iLoWO$6`P[pHao"l2B>m\'A*a:It8<9O#K@@)2m^2#6mm]gNaTZrL-dEeG)m#U+k_J8j4\'p!cnRpA+:&02keJ+_f-4U+@PL+(EqRNl*B^*+"!X16*@5KFgHU+XFk!Xm4H;B4YYNUnk)!^HTBXD7A=JIHo@`a0^!Y0Q"dJGjVWV3-\'Zc63n`fO8tKQlIN(Q(;3YE:6"_kUe)5Fkbahe@bNkfR\'pH`]_9of*\'(kB+bUCn83i9F?@DKH\\^@Wi_jCr6qU`KX]g78T0>IF*EG=aZ++KeEI<pYY*NE)<;SIPSUQ7V8U5LZ#c[Yp-s)RZsZ@rN*HuR]??,-F<mp!27Q\'n&.SXnTMHhV0FI5]m0/AgG0/XR%,[H5Pr.u+NNP+.r1St:DlO[i`$fk"N<nO:Ypa0.o:%NHm@HhQfoE+ELKaiVZDA\\BcZGOCtcJ%iSWeu`.XY?kN.Tm#hWIJWS]k*]lA4.!/sQ8,r5SpS%kl^!`u;m\'B9,E=bCXL$2E\\<.neDVVblRVT\'?gph?X$5H6-_Ef]s]D1ZlY@c"G+g9P*BiD!%7Ri+P%$t:Hl$ra1htYLUM"JV!:NZ!X[;+6lZ4A\\lGMRDnhS"7L^;M7W4OUKEa,1T^b4aT!Da/$gXF:!>*C/=^^3obGiPV-BCF5Onb0"JIUkt?,aX<\\h^[=T6I3ckA**71Eb\'U*eWRA&l*ddkYf73\\b\\+(Em]mI6TN4]N9q6[N9C=T?+2U=P\\gtB#Ha*3j0J(1Do`uK/Z]X5?5]Y(nXYJ0l)cTa)-T$-WGS*eh2?c#<7X]f:np"F2bL"kL3ml`\\B`)^>"Z\'ZA&m.Sn(5K,`JiLsfk/oN?@jn@I/mskB7aX<]3UEQB[0,jg:i\'S#<,c-`rO[83d\\at_4^0\'/p?F"*5s8Mu_e>X\\,OT*](hL"^V6Tr0H@uicrqWXp0XBAIo:q:W.7ZA>ZmbRb9J,5@&0?%du&4-XG`,UC9-0nl??-DVbrpuc@%RZ!]Q,];3^,];b`M>*-2(`"=0Fp`EOCaTcSW]-[X7r!J1MLXebaBiKE.[=-$YIjpU<T2gF+U!hJsEiS*g2fd&\\l\\q>s$LYfH5s$Ag=T.P]`F/Pgs&5i/1lGRMOT&KM1Fsj2]?<ZKg<8(eT#]hL`CgacAa-)*N:f9]tE`f%RNIRl>7,hG1;;hu<>Y0qD&9!tRM%L<-.s\\Zp8@;JD9*VX]HRnkdHs,)E]TD?M15.sqXY#s6>F,=[VG@jh`L@#$DLpu7\\?Ecakm%c3`j<1Y;CcTCSXgU),#mC/SJReJ5B)Vj/[F_f@K*,.\\\\\':]44iu`dKEHm+_p?_%kUIVQ[1@k"%K=`kA/qGa%<,S(bCQ?*kT7;=)4"n]T3_Snn]QnSrUZV2grVH1u\\:V^^n%:I/H.b-]N4IcE<N?QJ2M@]/[V9O*Ue.GhiC!/7qsP$sZ5b%MW"W\'-;^GG_D#]84IMabH5k&$8fYJLen\\c*MCtTHh*#p#OfK!cB-r6]R63n`fPV#2TP1rp5:5rENmb"d3<^*hK>.8BT_R(U><Kin_8L=gBo3^(L=0FgZbVRMT3p+qN=TciV>8Fm[(G>X]kF\\SJ<kks:197MF^ABP<hn3F?T-TZ\'STWLd.or`"-p0Zbpu@F)7GpTN?\'MRC\\?T2CB$qk2bF":4NgV#2`uTBjG7<SmN#=G6p"*R.\\T=Z_O_+$H.9"I-q!W_4qgN`V`jog4VUF,!>IR[@IFXjrOJ.c$[L&+@h/ufsYfK1WH$M\'VoTD54o>rAPQq%\\RZ[#II5Q\'IN++<e/mbPM:Y&*^Es8DDZ6%`]H=]nm7IedQbZZuipGmOtdPM<N_PK$=d2I1LZAS0h1YJU8,^ADfs5\'#^TF*:.3SV.A26;1\'\'jkej@n%E<p;Xr]+W=8Ygrpc&#!sb:N0M(2m2fE#aUZK:9n\\l=![r3qGD:>@VGaf4.r,>PB.%<AHp@mHo?Vm+!2f@FGe5K.7=:"Yc<tR)Var!\'TS@Ds6+`d4HF3Zcm:$hT_QW-ui9fh0UhgP$U2JU_ik%J#4Gd2P/IJWS=ZY#2B,7cs0O?(0>G3gU]$p\'_`g(HJ?J=8B5RdoDS?[QkIBr<6lL.^,^ad<^QbgHFSVk:D5f1mAJqWO\\ac=pU0iIsjWVoA]4f>!d&r:o<5@L$V0p:btP#!L3;F;`ijrU+kq%[Fq\'!j!@Y0uk=YKFgJk@73(l8YhLQO"@EXRT#S8GHO\'^UIUAsd+U%@[N9e^1".!2+8`?Q2^tgsM\\b8pPIAW#05n^)^c1.uA\'W.dA.,l5->dnohE>J=2e0i9BpU]N#nA]g_`]<b85!i<DKs\\]4Se\'%Aj6rXn>qjFG`e!`ju:%H\\D,u^Rr?$o/;[+!$mTQeUr(<BK\\q^@Jh6@(?Ibif^Bo&&).t56IA&;R&bb.8&\'"6[gU=5k9C*!hA;sls>.+/\'.nl<a_/-#+Hb3k4(6^N!47BiOfq6\\;#IXrdZFg\\dYIsEuBt=04b=d;e*+OsI2jU&AB$H3_e9jZ\'e>Q7Ah1mM`\\3bLbkg1KMIG(o;Agg]_>T#Aerse2I\\T?!b\\S0A7e+nhJSd67X0Pq-*gi?&t?/h$k%-F6#P6N+Z%$0[hYIu872/Cd-=XE3Qje+K#$M(KUXJFjZM+S$sKFi2!&l)Y_/9p5nn;0>3jsBus4\'W*@<kj+^&hY2YB:aCgo`+Eu%td?8[K[0Z\']37aP<:[>gph<5C!tQ?0>%kfd-%$NDB;uqI!L,>E6kXj\\!kVoamq=EDZ2$`r:A6qJ)/NtY:^cVmI0cPKGg)CZX<uo\'p>TXd5Ts11MAUL(boJf_UgBoZt2u[aah=E`)0#F\'q]fL9UR(8[;XqdBT`$(T-Fd%IJ9:(fqmBV5QCQ*8VNd#NVN^J($D08Y&*1-gMRC&-;L(u<-Y^Mj<pD58aK1HXY^^;Rl5,ph]6t?p"\'k;L\'`9:.t-p\'#Gu.NcR>7RFT)+2O4hE+8R#)W*BSG_oKVH%;j%L6@Ds&=S<^_LSpQ&)F+de>br(?tTYR)p^A[c[c!:X[Eqd*(Nf+4/KFgHU+br-6BhO&Ch!NUj;aKAR,*E9t/S;_nShP$\'H<XQj]^a#:/^(KEYB8$[4#^h0Yp02E>_;du>54UY60ZhKp?gUE*nn;S[s:MF[dj<+3h%d]o^:NsBN_rjXnaHnI]k:7nFbC?:RX-)`"PqJ<ioR#\\&f\';\'4gXFn\\l;OQkiiH+-?i81QOd"Gg*D9T0GR!c5^fWHN3s<A^0,<A]m]2.Ks1a0f3h*4T6YD9DsAG*dBpkP3$o7,):r1AdMgD%^o:\'mGPg5P7#(q;p)SUGk#7b<qYe1%t=m65,eJH?iMm"p@Qg0QQ[sKF)/8?Ef8%c$#=\'8+\'>4\'L!o=Tq1>DE050%HCR7\'[(]K*HS2kYR$GRVsImFM%qWk=DfdCG^_mC0M@7u5mBYpL5,)/mKRJ`>@SXj`09Z36Lc#d:"C6`LqYW7((D"F&d63n`f&-^"JXl+OPT76Y$Fk9nH2hhhbDB;E;[`fHgm_Af$KGukBg\'[fa]-)2i_YDC_1I>g(<l12`Iq!Erhg4UjUr\'>2#?THciJ&;I,qgo)iKiM,[VT+A)A*]7<ifH1VS%+E:SpS?>7%q3msk@!W>(!jc*S1/+h.VI>;Kp;$naJI^.r5T`obKK]mB?Dq%DhY+i+ajnB5J-MG$P\'b)iIQ>=h31;u5slkMEn!cThI-@-Al?";b5rX*P(iiVpUlrU84adt@Y1\\[g/Ijd0<apCSX7VG-mC[t7tiL(V0!kCNjFOp\\Ca&\\`FAq45-$[;%#CLubk;_NRe^9:9.N0SU3t0)^u_SKHl*DEQlP4n?Z=_$+n5)Du8#;I6kPiIQDfPRp.e+iFt%dT41;X3,GB`lXZJDS5rAgSS7lg(N,HBd<"DVG&Ee]^Eh&7in\'t]\'Ei?\'V7fNDsGtbO+$/YB>Q%MK($%!7kB*JhK\\&idh;7X[Lsus=:,NdD(T,/gmjNhkF?T=rIloO4aZnhQm8EfQT0)$X(TbM8Yo\'ajthe`N[@JhZuY9Nn7VdFV&SE$m`R8uS3D@IhnFLb.0jYf!<WN/hkW\'sie.t?f^Gm0Qdr-<S*^ID?MjKcT+lM\'kcdfdAnFSY0p(DI]Qpj-,Z7uj`n\\qOF6E&3:C&+s&4-j[imX43X/*W4Al&9r2(hMr,iK1kg^q6^++O49>X^dSPD$*8/[IF\'I?S6Q\\c+kYYE*+p"qWsU((bj\\VrY32O.)BtSpRUsYF+h8KfO[jAM2HZXBDn)0.!#^clGg6.f#9]-_5?W.JMD@k-Hn:,Wtn`PGP2<U\\KVgQ]Faf\\IUq&0Y"XPh07an)N@[Qb<EA%O5?9fgp1LLaX.B3/e%J\'P>;g[$]QJAM=P\\B/o;K(:REgZ^2n!j[;(shf6kHA\\1`=D63n`f\\5.M+&mD_[BpN1OhK`b\\BR?#\'B:jV\'o`+-MO+KjUZt5P-0q[]ffq3rdb:7ArfWi>A?LF4oT\'>(CGEU5D1&h%$^D=9a2]imkDqYiJfsKbAH4`rpC!3<8p`I1!JRQHN,o\'bP0E.Y_h7=V;g\'Y!G+\\V$dcJ,dE1I##BR^?Y?&LQaP^K8N2(CuHhjnerMhj^YbQKI:&+?K,<1X4a*r8Sm]>m+ee%gI)\\LoOIUmb5\'Ap+r];>C/)+Ub)<k)<RB[B:jTqd$!nFqU;)9PZ7GLF7EHgQNoN=C$U?Y/kCl3,cNBXRplW5&OHaHKFf74e!>ZId=lu>br7pu_R0"2j,YQm&FSDg>9[2I9$&u.R9s!ClD^]@qj1aF\'$RQOG3ml/I%[Y7f>h"!A4]\\X(S/;>qWi+tqXs1!FUq*.[S/<saN/Vp^%W/R9$E@TQCPBQN>e\']MMphT))Gku;W4H+@_O0&>ZgQ)daepnr*[5I(uO5@TIFIMq<kl`9ILrAE+$dpk:s^O\'jQD8@,/83nLp6ubYc20B>K1.PXF/0q;J-5:\'uL!1/,RB/5F:;X]s\'GX=\'Wfd_r_Z,=fat46Do?OqM%$rop>Q2K\'l=_p\\o&/b;nA8\\`!:V6Ft"`o)2tiV\'QL>Hbd;WnI0\\pYMBY"Es.a&I`/h,qrsK>IA42n52LX+bUF$8XQq!ZJT"Jrp*qkCAr:\'c\'gNPkD,3-cPD3n@[jgM6M0WNcOPC`3.?>im]C?[qWO]8P(\'+sf>f9fMu`"\\K=Z0h@X_Zd`oO\\nSnlu_@89Qm.FZlBhg]Ri-d"-gS2kZ>VG3pnf&ST:(L;-FXL_&RG@A]U+:1$(s!$*R0>;,..1*s]#$DAlJ,fJ8R@32C*),\'!m_&-dZ[GDsk1sn/[dE4HDmoUe@riP:WUSMg_nU(?R9\'m/i!Va23[\\WUBsVEr1/%JI^A9<D5@5>RgBkXMl)1.;AB5<"B,PR8+sSdal;Vh22>lcD1.p]HZ#\\(3mGLsnlIDs(]C.q?GVQs*<\\aa]%$42OT-k</HL%^.5/FEAp[-_e>cCM*oT;Wb0r_K9^M^].mp9Kb3NCtcqe\\p(dNUiD2/=!*Da:g^=f&6P?d>q!0ZqJ[&=Guo<c>Y@`n7P+V%CJH`C[\'jkF?T=3D\'K4/`I$R;Y,1rM%_8&308e)63nb&Efb"9T^W$Fc\'pXN&\'=)b\\2mth8kSTDQN5dIp$fj0S#qr+=74-SO-HQ3X4%lLFkS>?jU4IJV7o,_J@T!;Tjkuuk,NXUX&fg\\Jp+nCX.\\r3%4@`lU3Xgj&@8)hKJ09qnD/fOZ=Q[g)Dt21fo<Rsa:buCGB)Jbk63LdYAVYU8J[E[GOT<><qqgqK*+K(T\\7&lW9q(<DS>_oi7a#&.TDMN&DR`SP2\'a)Zt]#Mnod]K]&JStia9tV"[dGV_-I@80jeHqY[E%X/>>-O,r1id</-cI">6,#n45&!LUnb0#$9iO2\\K@W;;ulF`Ti@CZm>OlY*t+k5+CT=ET>($k8ocr=k]%/)gqV/=@;?p\'MA_Gl59G$[cnRA_Pan!rg1A*+bUCn%MoU=D&!ak&4>$%&f)ruXt6WiUQ.B-QI`mOLG6/NX.V.cabia"Ct<=:Y*O@eP&-LrF+\'!$:I"f"[r1"qe8!X?iDirb,qIs4ne\\,o>6T^.`FK!selcY9WDc<A;)VFX?G54/Hf&tt>qt59MLTh)XB;_oJrJd>@%"^ccULO.O;DZ^Wg/Nn"H$]M4nc>=DYr[rT+\\"KgU(O:kb3dm+N_dKP3j?@r:0O=J,d62q[VPQ*Zoh&dBI&s,_8SAOtk;+b<,b%o:L?oWGjVUaI/Zm0*<UI+Ha!Wp[706]&R/c_[f!0h=#gEX&gq\\+L5M*?cHHQn@-12/`EaKgpg3de%U6WP8P[;[;Of(@YFrii]^e<OPRNm#GHCrZtUiYI.uH@0>-d@Z\'?:D@K[Rdl-lQNJ,6=$6gMuUh`UMS1M)?<\\FMO*9UN&4qt<C\'9u;ElbE`SY4BP9#`KIL.<NDEFA^[AGi?(3i[;+6N))M-^lR/Z1U/kH$>0WKnHh?MVGOA`8hD$1,&420_A3$)hF+"H`#U+j463nb3AbG?=k1nX*YJ#\\I(IABNKFgHU;8TbYgJ0p)e>+krm92g^+bUCn#U,s5O$<F(UWo&/daHS;HRT7f#U+j463na2_0kdf@`=3F3coW:`>?q66O4ig&4-XGKFgHU+bUCn#U+j463n`f&4-XGKFgHU+bUCn#U+j463n`f&4-XGKFgHU+bUCn#U+j463n`f&4-XGKFgJkiCX_+KFgHU+iHUl6,X/X74*[!63n`f!\'gc$0AoY?63n`f&E4F`!0P*k-A2ps#U.,:(]bh56VRh0KFgJ+="j\\D#)AWY63n`f&?fIEL^XbN+bUCn#U*Nj#S7jnC-i1LKFgJ_Je9+\\37NTm63n`fGQf<WA8nIR+bUCn#k86kJB6YF\'1)sJKFm,XMu]!VTdGF(63naQ.i8:2K0r?=+bUCnLfZ836jAF8&4-XGKFk=p"GdHr2\'IVa63n`@_$CSi*,7eG+bUCn]Rg_<1-!d:&4-X_/?%.i!pYjS?""?dMu]!VTdGF(6HER94H-3T]##^R(]bh56VRh0KTO(QGSj:2FG3;.0EOWHLRJc@#U+s,n1^SCkR*O;?j)8o%Q,D_O@+]D($"AsPND8q/$HU+87.&rjPZ)Yb&,Fentjs:Nt!sPk\'d^Ne!;=Eqs6+!QnQ#2Oop%l,=#dYW!OW#*$PmAZusPD\\!TC?++O3.r1dhm[U_J*2;)T0CeZ"WP*GL!<Md7LZis--.or_g3HA[%k0:6=ZceUa=1`YC?G1[0SiutKT72[W:cSB03LC<uVQI`>%Q,D_O@-tFR\'u_UgK1Rb^#\\6bq;XG\\o]Z&[9NtB2[,jj4RPJGH8kOsL?&&n1Y.EnuM%_6H*BLPnK*KcP[VacTNeYFkVCc_+D5a_GT+=7iQk86hLZ:esgiLf`T>eX!#M5tUX*XI(]6<S!l+jY@,tqMqUoe@[VTGJOFjs9,^A2Bb6]2a6maeMp+[$%Z^pN2TXpm73p@CT6$55`gic(FOc9D,Aq6RSQl-dtS8\'?n4*d]H86c-4<@`8[WoAo&rQ7H%>B$He-T7;=6V\\%*>C\\?uC1M4jEfs50Y7Rl"4>tnf;B$6A.m_8Sdj,Q4(8sLk@.TE?N\\*dC3Sb9i-09j-@T7$3$s8MuY.@HTl*BJ:EZ=M(0%mDDrP^gU,eurFF@`4*!p$8NRVcTp"X`s6js8Mc-\'>DL7Sp98ij,]NIW*6Uo^juU&pu74!=5:H6o7RD`RPo"4mjL7ZqrEr:IfB0+_]==LGkTg\'jXj,t@+DMi_1Ft*"uU;R34"])D;*\'8hRduMnD*fT8L^8H<4U0AB4i309M1$*Um0Bie8f8gO/R.opR!2!l3ZX<YFV#M?6LaX7=&"5G9#(tX`n;I?`oKO55H\\d;&B3WTbL[j5WQ44Gc4T@;TFe<++F"DR/Z)s@DdgWCtMS\\aDob)7>i\\!\\73pa:#S;-kKfJ+=1NA5o&\\\'<d5?(3e<nQ4^@p8rB:aD2O[gHAa7\'[2*-&h%-ergm9aQ"sN#\\AYX;Ws2aKrge@8@(,n+"t5DtWDG96MkVN:skJ#B2ATWIm_8lQ]j8p?gI:F,dhDfn[5Q]KcDcO"ukl>DEBb%5i>&o0MRI\'1+h@Yaajjrq^D5<AnR>6uL3%;Z8l&Z6uMFI+j`\'+aG=b/ZiBpIUgEYQ)H"P+^$S6qsM\'^*tt_dV\'cYZ$SJqsr:og6?$Dj@cqM\'iONG7F(3m+sBpXP;eQ6*0SM.S<,$D`/r+\';f,X/P&4QDAV-;L\'ZiCMfuT0@[4d[\'6":/4Q)Eq8ImT.V(I*KXQi`TP]G599>:cT1/.GpDnKQn`)3GO@"6Z5O-)1=r[7>H_?rBpV?]oCHN"?+Y8sg%(d8r9\'`68R&JnWMulfp;`.3-Tbo]OqhK5B$Ds@n3VDQ^]!P<A_<iWg^W^Aldi27ER^paAoKNk[4ru1gnp,X06nrt]8#CGnjbN1/lt@,Ai=HI*!TD=*10p7RP^mR<lq;hXS`Zi,a=RpH6gt*Q$4QLRNs,$hKe:LE9ma!=D6HtXW1<\'*TVI,BHYX7iJ&;\'%N@<BOFSurOea3,K,i_\\p*H;`UYLqS6f_C5L5$0YHL8,l8n=-t&pAHehJG<0j&/cQW`5s<n\\l<fTe9cU9:%7gCXt%^hom%==L"S?A+D2(8I7mQ<&&+Qe5K-X08SqR289"ZbL5b\'JK;t`Vb]5^Q,Z>R]Anr:?M_`4ADAfPr,R)[158J,LBXgi20S]b60JXh69O83S*4b%m5Fd0GjDK@R_,kCPVpe0Pq0b#@a`hn/R)c=,PgI$rpTl=5-f:Sb/ud5\\Dr/VPH*otWO$3]Rdel@IZj34n%P";PulkLB2?$#k5YHkO<pW;lJ?mV%9f?Kjr*bl5"Jn`5&AlUTk(*\'?[Xfq-;-taZ!+PM"\\HkLa%DUHIJDcV5rTGW++O4YTLD2Am,t.)4rUeEh7?TeK<jR(ghL"dg6-?Z6B9aX<NB/Sn*]#D<u0-13W*m)i]]r$Q<dGCZ^PtE>,nqO+K6h>-+-@WI\\rsYdJmG+QE,1.eILc3QHF\'i8kr#lg9U:03NaEJi.2N$^#Ee<CY(1a\\n%l"XQYT\\1Lt9Fh/uf/gQ!:9Ie_lWn,_"A?b`81i0OO$GZOkDrT3JEn%Tt$aLC&U>JcC`s8;KZPkt(=a./c-^OEl,@@Sb$J,fK+%].jNpbuNJK/oS]4u+5BPW\'YR09_gBr9k!AQM\\0MeC`I##GEYA#k<_gCSKRmDkA;;Pa%D?4Z7BD9_f>^DVVa@\\!XNK.k\\C0Va(,/Ao%5<q9g<P0XK,`=_&9^PI@o:gEqn#4*Hio.cnsZ>IRA!d\\p$<n;!?`;bf>!S@01c>UXg:N#<<#FRq,:dp(rt?@VqHiBAp0r,P^!as"(AQ+I,&%#ET$H&6n9\\]<J_Mq,Oiqj-AM]_h-/dWs!".7$VD[$BIYkPo!jc;?<=YLp5*s%[L_DeJL8A5ne`=1M&oE1`*E(/.q5hJ(QBR>b6q==tnLqqL#hl$rNP?d)f>[V!dQ<F#Q6O$-OlRDb)(j.8D\\EcQ2\\5Q5nKf;,NE55D#H]5cu$B?F/EHKqKh3Z\'6eWuo.V,\\4XpZ_<UI&o5\\?\'U.d?:RSZHa0hV\\c@.q_?"$\'U7iYhKh2<r#.";e(470DJAb5\'/l07FiCY&FZkF[CHR\'\\_ii\'=h7CtPu6^SY)9?IJi6P>@WbAtcVKfs6t]/ab)+]mKL>p/\\;!a_FOZcH_tB9A]J5M\\\\naM_;RhVZ!B]D@3;Dn`.ZZNsNblm0+;2+ROC.EC]de/m,>#]W%/H=%_N"TgR)\\qsM\'lme5kl,A\'llLC]aFOX!AbDC03(V[LCYg9aHFVe+&;=]nm!+YLP-nt8dq[$B>&IikX^X\'A;l;cr-s24!t,[@1&Fr5P&X:.`cj3Ar?ErsdGCQ$9=Xf&rZT/dFXJ?=&<m\'uDg;%Y1s&f2etT;=]Vj-HTNmrU56Rs.pjYH#dqGN>aZ$a&/a0*I4CDAeJ@6.TNX]iekbtHRq-@<<C^O=-kLocVMMfS/=H`9#!Ro#BVX=9&l]6gUAOF?DSq+4u7&dO)%+BSc*pI]#\'+3O#Xd!\\oZ1\\=8j=s5L39tb=+4YGiFRQ,pmJsP=NSHDr*V*bq-525"8XNI+j`pTenZFgt6Ej,9u6c$SMoP<YWlt%mQSKkbOJHb6;VGZHFjN@;gea$qsE<-\'4K%TEW)&QB8q8#FfTXD9\\V52eL+=DV\\L2IXQL?IJ`_>??tZ*f3^0a3bm0CR+5]`ZrQ)K<[GD#HAr-WVb5^XE]Z.Z>0O6Kq:IKdR\'phD@m3IDHhQgcNkKtnX&nKFjJ8TIFR@fTWiN;6iJ&;IVP\\t(,CK=Xjl/.=]p,>0&97I#GFOB%pu72E.[q,UY:`t`UjMk(jiWiEm;:UdrPq/%;8U%=^8k;:=pZ4.\'.6MC\'Q,J`rZ\'S,Cab:(,YlMLG4"#&m.6)L/!?:.%L65XC@(<MK?t>[KQtFD1spaCbr=nOl,BcMHM$D5oSc?c-B<ND_$;9)^UUI`m.UkVldi1bjH2r+VE=%<PD\\]"pV6_kW>+O(b_6h/F3/c5R^?WiAf7\\6M^.1L&VWIIi=GHsI+bf:,qi(hI5C2u:&<`p#2>G_%.N%Q=f!]kEJa;55JQ8G$R8-"Lp-LLq=>7@iOa=&Icm8GDSQ-nF!V9Zk.^lpHat0r_IL^SfWjJ5QX78cRVOZ61;prdmnUl!b&^cAqcV)?3O".h:`:GGgm0PSJ"Ml:IG]#6il1\'>W**8+P)b1p&;rj.O$EVgkp&?f^HCgip;aS7`m0#s#[Lk*LdrFS\':i8Z[;F[ldPu!kW$1K6i3ZHW&i!1@s5$cb`MK]g?@+9gf,&9saPOUW)`;@U4c?pK`oitDSlCU9D*@F-\'1n$UJ]1HS[.X.ID^Qk-^.AaPV6)8N\\3eoe=5bS&jXMS8e`5#M6_u+(\\r*J*G,s)T&q+[K7f;+DRA;EU"o&_99Q5!:dn]dI>pL?,(V5;":G<PDo?9#8h<)tObA1tO]XbQO$+]loS!-/\\KoN!phqO%GcdM1+JK;sh;Yl4,gF>APeubuX\\T5ZH($!c/agO2i3Q$U_cd0q`c-8sToIKXtJ#24\'kp&?l<Vt[M:$&nj]M#C:20S]b60JXh69O6]Rcqs1S)8PXXn[Ys$HYZe?$DjM)j<Z8r`#jp71rbIF!^L4dn4Uo93/:FIdtAnLE"#(k*qa\'S#g"5eZ+n#Q56fk%F_F`\\"mA<POR7<T/D,[K<Xt=cTa@)fW[\\r$K:<a)jW\'[(483F1hfVHgpsbm!9_Ro\'=0.@q2H=PRbPfX/[H4`0k3]"o%n`^R890\'?XiBSZ-r46b:f?s6&F\'rCIjW2C3W\'=l*FUgWm\\&b\\]nn&Q:]d[puR*Pp$1(kBFscs*+Rg:G;m!*kZG3*;=NdjcTRV`RMnpUn%A8;GMdfbhLbPFJ90%"fA)Y/8ac<:djO:p\'O/"^$%>e2TE"h%q!./K^RS=4+8di-G>5s4DK0Bk2#D?%#BN.EHt5igp=X*MRY2unDr8:dr8opI)Di9eAkYnPOr:?Kq=5/hJpCIU..^lqYJ3rHFQl\\;O`l",GbR;nSpS8f9^UP1@qS"JKW[!P`$5bYM9[ZZ>./78n58uhS"-!R]68%t^l(u40>@3jV+R#KcRGc^12>=;r;:qF\'\\00]8,bOSI>U[%HhQe\\^X.;kV3g%do?C43:0kJTm=5-,+1"1a"q@"T@D_Nm_iI"XBPG$RlDmR&(D>LKpR0J5Oq#`!n%@TQ[Xp$H#p4QaJHWHX_J:48Q=WcGE8WuaS4Lh)?[ZM^PVR*X?bbHFZ`J<8esB`mq7(G)0"Bhk(+oN0o&u&lhCsA893YbPq5#WMA<GQK?U&h1r%!,0/iaPn$!FF#Q&kR"_$N:g=J]llP`/4+KtjHareO#]Fdf..YFCt`=^&+8Sne,kpU83oD$a.<9T`eP_a]YR3Pa^32:W5O:F(^]*6E6RbAf&SU1_fD@L?&_+N9.&1,:W\'.2\'ndfKSJgF6\'Jd-+r"j(Pn0jj8AMp+$Y5PY[PGF^MI&E@QMU#<kWg%3OWL7nj;K.ATd=i%@5$@1&l)7<k[^kMp21`jlOJZhH%L7E;SI`"$;m&F![[Q&V"`"Ph^E5?#nFd*]K9b3,RJrj,HWM?d1B@3rK"`Ed/kKIFU15F%_R06]IZ8Hk<m+KFm,_k)+O4I!)/RNul-XOGZ[T,=[W*e>SM2)eD#WX1/Nj]J+_-^Z*\\-nF(l,>F(3#g"EZ%0O*DFFfR\'2]6E]rO\\HU6&rsPHm5farr;Bq5I`70ZZI5dY\\T2:ok(tIW\\7E\\oo0LEaWs`h#\\5=$$c\'pYq:n^3V<gN*\\`5@?PIQ0;o:s-.F:jCE*g9bR2g9d"0aKi?_]m@A<opRaRerCb49S_WU<^C.Vm+o9tN>aZbDe0<^/kYmOJ,J=KRl5+u^/^Lt4tHDL<qV,e.NI8*261Ii8m5+bW]X7`8tF01mAlgtmf2b)rg`Peo9.QQ,UK@a<624=pUJ@_c>k(F3NEdQY3!inNuU/X%N@FF,u)HhH2?d\'c^m9]r.EToQS+Q`<e<TUMA83ql6HU@9T",ebr:.LgY]GSeZ*B7WcGmGoGB]8E;6>j%>u#U53%SXjOfP13oYr?,\\UG4rUk2URn"QMr:0C(4&:l@3U1-fA="Q)IIk]B-1&;\'l)1.;mBk@\'V<)[=c->Y1\\*lsC]jr06q&>PEn\'?P*bRtG=pAOidT^[^[Y.<[5oA;M__q]7P*NN8FB%dS:LT$/<IXZa^09]KtD92gH\'R+!<%3%3m%h/^pk)4o@*q!XSKic,MB+7EYZIp,Ro8J!h.ng3l,WZ,<(m%_l\'<C=;.3%2p6e)QM@1jU\'damjB]A\'c2gS@CSF"NXOZrOecoqXu_I5Mi.2kQk2GUp8@fCh.NqsCl@?F+7gP4sNAMrI,s#U,(fot^.[bJPo-4nVchC2.\']*bq%a*;JDfog2`I7#/(TFlSH?VPL!jVlo%.QMJ4EQuDm/Fm@H_:1eqMjd1#ba<Qb)l1=Mm5QC2BG^B4;m@.lY%A.:_$XI1-#U+tV++O2C/M4(pNuhA.Fk&A$>]]20V^<c=QS2]0jo^0i2=SASl@lApM%8,]^qoO&Rr>1$VN)ZY2J?OQ.KT<,UL*-k\'1)sb,ja3jBB7-r`uK.oG\':=4Y$/5JSU9e8n%JH:HG@T8ptnp@6<BOBLMIL[J<9i^Ue-b^c\'j@$64!B4@<&e8eF7`Q^!IK@KFgH[&GY-Zog2`I7#,Oii.0LlF_f*+Ql7hs<\'_d2aX@YNL)N8%W#*%^KNJ6KM[r,jR1KbaIShb?Kh6Br(\'+o4++Eu.r`A?F475(lO6$"EO$-OZ/&6pjcSOj?XtV"7_#<8Fcp];"!k;Ue$XI0R*Nhh]Z6fL6KPT/?iNF1>i:DnRTdrfm"`V6O+EW_PYlO2.og2`I7#,OiTPTH\\>Jc=:1Sc`Q-YN5DiVE<F\\[f7kGP(+H1!dQ,g2"sR$`/pVPl>\\^pbh==^pTkjcSOj?XtV"7_#<8Fcp];"!k;Ue$XI0R*Nhh]Z6`r5&f*\'&e>5g)MA7XRAnJJef5BHXGmU,Bi.DQ_UXDYY9)lkg(E^lH\\2Mk+Gt,Ko\'dgj#\\6jUp]#]P,!;DCtTdrg2_mKcC(tXK\\50p/D]#\',&!;DB^65Q%$$fHJ206Dn>FLW(e\'][nD_rhp16<BNc$fHL(60KL+@KG7;l@lApM%8,]J7;b&CA9od?K__0@KG7;4pYG)67dZa7D7%_-ILdU"Ak%m6OfZ#e-fPj67dZa`<W)p9S`jk^Shs[_B_0IMZAWSD5cFbN-_0J9S`jk^\\ApnOU88mmMGO_=-uC2CCrfdXpm79Sl%._KaG!amM?su/i"Rc_#:!6kR*O;E%M,>`jMLpcSOj?XtV"7_#<8Fcp];"!k;Ue$XI0R*Nhg2`OIhUn9IL:ckRnG!k;Tb&A#r9=9/)RHD)i_U;OAETGZ:8)EuKG(V7J:=9/)R%mh)#&.@EF;(m$F8T_HX!>OSJ:rDH6og2`I&.@EFnNl@_\'4M!t0C"7o0Sp:k,(O--)f#.1UL*-k\'4M!t00TYIA3qhtqaJ3F\'dh>e=p.Z\\CI8Q\'B@I;p@6uMqqo&f6MbJp1E5/=f]##^R>`/T>EG_Z5o8J!h.nka&E52/jFHHm7!:CZr6<BOBLMIJe0s1sCI%F1gFG1%+!:CXFKJ##\'(;TmC?K_`[k\\r*T.)rZgL<h[@Ks!*Q(;Tn.K@!%6_udGUe-fPj&fn,D!6)H+eF7`Q^!IK@_udGUHk<m1KNJ6KMgD\'I9VTG4#bW$dL)N8%W#*%^KNJ6KM[r,jR1KbaIShb?Kh6Br(\',-0g/,]M)>-<tQk0Y`Ido_f+qnDdgb7rHXtY\\Bf-5`S>T7GQ4JQ6H$56kLgb1hs?"?8QJGVdKckRnTiE?@\\N,(ciT4cX]?"$&NJG[:jTo2U#"`V5T(V7I/3a@RCMK*L3iU`"STdrfm"`V6O+EW_PYlO2.og2`I7#,Oi5V]DN211um06DmSYlO2.++u7%+VqllU0d$jPNZs;![u\'rTn^lLl@lAp+Vqllie,TH-H#tq?doHh@1jT`70(<:2Uq5A7_R.`-H#tq?[NEraFmXqpPX?k.nl\\T[0WEBf7k2-c_qYk_Lu"kpPTPK(RYgBi-nNVFG3;.\\/#)Zj4[>Ik8EqZ=-sO,i-t2^kTU[L!Sf?nKs!+d%bDnT@U\'jepcP<XkR%u4!Sf=l#[Lt-/:dUd^!IK@dG\\73:lK0W%A.:_$XI1-/:dW:#GI&LL]qb4W#*%^,W]1g!/bc5W8[?,HD)i_L]qb4p`O[@$*aKu(\\L*rQpc^F&O8(R%5iO);(m$F$*aKu(E\\;_1*IFKrM!W^$Bs[m/HR??[@r?$1[9[s0Hh4IrSiIV74,qS\\6m_n?""?dY!i?0\\2Mk+Gt,Ko\'dgj#\\6jUp]#]P,!;DCtTdrg2_mKcC(tXK\\50p/D]#\',&!;DB^65Q%$$fHJ206Dn>FLW(e\'][nD_rhp16<BNc$fHL(60KL+@KG7;l@lApM%8,]J7;b&CA9od?K__0@KG7;4pYG)67dZa7D7%_-ILdU"Ak%m6OfZ#e-fPj67dZa`<W)p9S`jk^Shs[_B_0IMZAWSD5cFbN-_0J9S`jk^\\ApnOU88mmMGO_=-uC2CCrfdXpm79Sl%._KaG!amM?su/i"Rc_#:!6kR*O;E%M,>`jMLpcSOj?XtV"7_#<8Fcp];"!k;Ue$XI0R*Nhg2`OIhUn9IL:ckRnG!k;Tb&A#r9=9/)RHD)i_U;OAETGZ:8)EuKG(V7J:=9/)R%mh)#&.@EF;(m$F8T_HX!>OSJ:rDH6og2`I&.@EFnNl@_\'4M!t0C"7o0Sp:k,(O--)f#.1UL*-k\'4M!t00TYIA3qhtqaJ3F\'dh>e=p.Z\\CI8Q\'B@I;p@6uMqqo&f6MbJp1E5/=f]##^R>`/T>EG_Z5o8J!h.nka&E52/jFHHm7!:CZr6<BOBLMIJe0s1sCI%F1gFG1%+!:CXFKJ##\'(;TmC?K_`[k\\r*T.)rZgL<h[@Ks!*Q(;Tn.K@!%6_udGUe-fPj&fn,D!6)H+eF7`Q^!IK@_udGUHk<m1KNJ6KMgD\'I9VTG4#bW$dL)N8%W#*%^KNJ6KM[r,jR1KbaIShb?Kh6Br(\',-0g/,]M)>-<tQk0Y`Ido_f+qnDdgb7rHXtY\\Bf-5`S>T7GQ4JQ6H$56kLgb1hs?"?8QJGVdKckRnTiE?@\\N,(ciT4cX]?"$&NJG[:jTo2U#"`V5T(V7I/3a@RCMK*L3iU`"STdrfm"`V6O+EW_PYlO2.og2`I7#,Oi5V]DN211um06DmSYlO2.++u7%+VqllU0d$jPNZs;!ZWKG`f3(UjHFY+F#,R,W`H6Jm\'4UfFONsR2Jn?9[WLc^SiqEm#O0gFA]s>eVsi<F-[oih(GG41[;0r/G#hXEqtBF?c\'ro2qrZU/_rhp16<BNc$fHL(60KL+@KG7;l@lApM%8,]^d1l$>e(MC3+9mi+lgV(+$"@P]6<T&h:8K\'BAL.A6(`i=(T+(,8q7g@FQf)HA+K3]UsFPl"(F/GF66/1ccO9H5(%U(I_I\'e\\N>-0kQB[#f7k2-c_qYk_Lu"kpPTPK(RYgBi-nNVFG3;.\\/#)TOro2O0rF\'Dl`QF1Gib2lR_.=_D6$O/7XBCWgMahI4JbE#%asOf7ir23p"<uMPqQLY>.&*c_mF75ZDD!IL=0qlZ=O9LDlsO,I%F1gFG1%+!:CXFKJ##\'(;TmC?K_`[k\\r*TPWA3Is1Z.^;bf?lgmp66Nnh>Ciet^&?@(i^C$a9E9@._>NAjJQUe-ceh%Do\\oXHg/n9IL:ckRnG!k;Tb&A#r9=9/)RHD)i_U;OAE;!(HB3`Y%p[F\\`#mLC-l8FFcq5<mq9p[6k*R@.c\'Bg;RgPA0:2WDi_/X:6+,87QOTmXab^CI8Q\'B@I;p@6uMqqo&f6MbJp1E5/=f]##^R>`/Sn_B8dHLWP`-kND$#FOEbOmTR#5p!#GQR"rmE\\__VpSX?<3Dr+aQQS2]`mT-Mt?1,^>?6^sN9A4UXgf_Lp-^DbbB7S;al@lAp+Vqllie,TH-H#tq?doHh@1jS1e(,+$*"f!9dn`4,l`\\&5*bsK?Yr&Ug\\ME:r*BSEQT?JcdY+4;\']mFrs[lSZs8Ge,N)bP?tVCdZ=.66aFqo&f6MbJp1E5/=f]##^R<2M7"KWM)CHE\'Q#-FIX@IeVZB9k+<?X#O?\'CA9od?K__0@KG7;4pYG)67dZa7D7%_-ILdU"=S?BY$INgT&.,*F)s9l:D+FuCI8Q\'B@I;p@6uMqqo&f6MbJp1E5/=f]##^R>`/T;Jn\'j)<o2lGhgSeFX(6m6cSOj?XtV"7_#<8Fcp];"!k;Ue$XI0R*Nhh]6UAtc2<?u=fs7H)=+Ce^T4cX]?"$&NJG[:jTo2U#"`V5T(V7I/3a@RC#K%p]I.H*;hh>;.mbMZ-h7-t8Ni$CB[VaQq=5WJM)m<DNL;.V"E?Z_.!;DB^65Q%$$fHJ206Dn>FLW(e%Yj5sVe9ONS8ub$_hJVi0O_h[+[[/)BHZcH<ioR*pOE2ZFBbtW6#(.L<`[eJQX2^rm+At`4R"Y0^jpk1p4]t6A&\\pkccO9H5(%U(IXZ0PY1t$\\HLq7,Sng\\&T4cX]?"$&NJG[:jTo2U#"`V5T(V7I/3a@RC#K\'%RI5GEOLt8\\4914q*Q(=K%Y$JZ]P:(;*]K)kPl`\\([ZY.T6<N8SNCXJlqSTir$B@!1E%5(hkW(WI0\'e<>/bfl;Gc\'pZ\\@!9l(Tn^lLl@lAp+Vqllie,TH-H#tq?doHh@1jT`70(<:2Uq5A7_R.`-H#tq?[NEraFmXqpPX?k.nl\\T[0WEBf7k2-c_qYk_Lu"kpPTPK(RYgBi-nNVFG3;.\\/#)Zj4[>Ik8EqZ=-sO,i-t2^kTU[L!Sf?nKs!+d%bDnT@U\'jepcP<XkR%u4!Sf=l#[Lt-/:dUd^!IK@dG\\73:lK0W%A.:_$XI1-/:dW:#GI&LL]qb4W#*%^,W]1g!/bc5W8[?,HD)i_L]qb4p`O[@$*aKu(\\L*rQpc^F&O8(R%5iO);(m$F$*aKu(E\\;_1*IFKrM!W^$Bs[m/HR??[@r?$1[9[s0Hh4IrSiIV74,qS\\6m_n?""?dY!i?0\\2Mk+Gt,Ko\'dgj#\\6jUp]#]P,!;DCtTdrg2_mKcC(tXK\\50p/D]#\',&!;DB^65Q%$$fHJ206Dn>FLW(e\'][nD_rhp16<BNc$fHL(60KL+@KG7;l@lApM%8,]J7;b&CA9od?K__0@KG7;4pYG)67dZa7D7%_-ILdU"Ak%m6OfZ#e-fPj67dZa`<W)p9S`jk^Shs[_B_0IMZAWSD5cFbN-_0J9S`jk^\\ApnOU88mmMGO_=-uC2CCrfdXpm79Sl%._KaG!amM?su/i"Rc_#:!6kR*O;E%M,>`jMLpcSOj?XtV"7_#<8Fcp];"!k;Ue$XI0R*Nhg2`OIhUn9IL:ckRnG!k;Tb&A#r9=9/)RHD)i_U&u5556(QPD;2KFHt`ENmIFr/qfA]Eg@@u%$56kLgb1hs?"?8QJGVdKckRnT!K7"-.4I45Hum/[DRnjEGr4OZ3Rfa"q\'L3;$*aKu(E\\;_1*IFKrM!W^$BsZR7Y\'R\\j=+$),^bD^.g"Z#N-_0J9S`jk^\\ApnOU88mmMGO_=-uC2RqZ[!aH;`;<Jl$N%Q-pa^\'S(R67dZa`<W)p9S`jk^Shs[_B_1:NrX\\*"\\DqsqXsa/YF.IrmS,Xr<2E3PNZC2N\\Q9BY[,me(\'dgj#\\6jUp]#]P,!;DCtTdrg2,PhZg+Y0C6OpfCSb\'O\'_kG-h5#[lBW:$;ot@KG7;4pYG)67dZa7D7%_-IEER"IN93K+C.Zc>Ci\'2%MqLn2&BQZZYTb.!I*YR\'qAU]#\',&!;DB^65Q%$$fHJ206Dn>F9!ON[r1%$ns@*V?5`moQ>])kQk0Y`Id

In [7]:
pdf_sha256 = hashlib.sha256(pdf_bytes).hexdigest()

hashlib.sha256(pdf_bytes): Feeds the raw bytes into the SHA-256 hashing algorithm to initialize a hash object.

.hexdigest(): Returns the resulting 256-bit hash digest as a 64-character string of lowercase hexadecimal digits (0–9, a–f).

Purpose: Generates a content-based fingerprint. If even a single byte of the PDF changes, this string will change completely.

In [8]:
pdf_sha256

'16b4413cee36cff56f0c6194ce069486f84abfbb0aad7db4e6b5913d671d5673'

In [9]:
document_id = f"PDF-{pdf_sha256[:12].upper()}"

In [10]:
document_id

'PDF-16B4413CEE36'

# 4 Inspect the PDF before extracting text

A PDF has pages, but those pages do not guarantee that the words are stored as selectable text. First inspect basic metadata and page count.

In [11]:
reader = PdfReader(str(PDF_PATH))

In [12]:
reader

In [13]:
PDF_PATH.name

'Chapter 57 - Alert_Case_Summary.pdf'

In [14]:
len(reader.pages)

5

In [15]:
reader.metadata

{'/Author': '(anonymous)',
 '/CreationDate': "D:20261019024030+00'00'",
 '/Creator': '(unspecified)',
 '/Keywords': '',
 '/ModDate': "D:20261019024030+00'00'",
 '/Producer': 'ReportLab PDF Library - (opensource)',
 '/Subject': '(unspecified)',
 '/Title': '(anonymous)',
 '/Trapped': '/False'}

# 5. Extract text page by page

We keep each page separate because it gives us an easy, auditable source location. Page numbers in this notebook are one-based: the first page is page 1, not page 0.

In [16]:
page_records = []

for page_index, page in enumerate(reader.pages):
    page_number = page_index + 1
    extracted_text = page.extract_text() or ""
    page_records.append(extracted_text)

In [17]:
page_records

['Illustrative synthetic data — not a real customer or bank investigation\nPage 1 of 5\nTRANSACTION MONITORING\nALERT CASE SUMMARY\nA practical introduction to machine learning, alerts, cases and cross-border transaction analysis\n1. What is Machine Learning (ML)?\nMachine Learning is a branch of artificial intelligence in which a system learns patterns from data to make predictions, rank risks or\nidentify unusual behaviour. Instead of relying only on manually written rules, an ML model can learn what typical activity looks like\nfrom historical examples and flag transactions that differ from expected patterns.\nML concept\nMeaning in transaction monitoring\nFeatures\nInputs such as amount, currency, country, customer type, transaction frequency and prior behaviour.\nModel / score\nA model estimates risk or unusualness; a high score is a signal to review, not proof of wrongdoing.\nAlert\nA rule or model output that highlights activity for review by an analyst.\nHuman investigation\nAn investigator checks context, documents, counterparties and explanations before deciding the outcome.\nImportant: ML does not decide that a customer committed a crime. It supports prioritisation. Analysts must validate the evidence,\nconsider legitimate explanations and follow internal policy.\n2. Alert vs. case — what is the difference?\nAlert: a signal raised by a monitoring rule or model because a transaction or pattern meets risk criteria. Case: an investigation\nrecord that groups one or more related alerts, transactions, customers and supporting evidence so an analyst can assess the\nactivity as a whole.\n',
 'FINANCIAL INTELLIGENCE | TRANSACTION MONITORING\nCONFIDENTIAL \x7f TRAINING EXAMPLE\nIllustrative synthetic data — not a real customer or bank investigation\nPage 2 of 5\n3. Case scope and portfolio snapshot\nThis report uses a fictional three-month portfolio (1 January–31 March 2024) and one illustrative cross-border case. All names,\namounts and metrics are synthetic and provided only for learning how to summarise an alert investigation.\nMetric\nIllustrative value\nWhat it means\nAlerts generated\n1,245\nSignals raised by monitoring controls\nCases created\n320\nInvestigation records opened\nCases closed\n305\nCases with a recorded disposition\nSuspicious Activity Reports (SARs)\n28\nCases escalated for suspicious activity reporting\nNo Further Action (NFA)\n277\nCases closed without further escalation in this example\nAverage investigation time\n4.2 days\nIllustrative average from opening to closure\nTransactions in example case\n18\nTransactions linked to the selected case review\nCustomers / entities linked\n3\nOne customer and two related counterparties/entities\nHow to read the numbers\nAlerts and cases are not interchangeable: multiple alerts can be grouped into one case, and not every alert becomes a case. SAR\nand NFA are example dispositions and must be applied according to jurisdictional requirements and internal procedures. The\nsample totals are illustrative, not operational benchmarks.\nCase definition checklist\nCase element\nWhat should be recorded\nIdentity\nCase ID, customer ID, customer type, industry, account / entity references\nActivity\nTransaction count, total value, currencies, dates, originator and beneficiary countries\nRisk indicators\nAlert typology, model/rule reason, unusual behaviour, relevant thresholds\nEvidence and decision\nDocuments checked, explanation sought, findings, reviewer and final disposition\n',
 'FINANCIAL INTELLIGENCE | TRANSACTION MONITORING\nCONFIDENTIAL \x7f TRAINING EXAMPLE\nIllustrative synthetic data — not a real customer or bank investigation\nPage 3 of 5\n4. Alert and case trends\nThe chart compares alerts generated with cases created across the illustrative reporting period. The gap is expected because not\nevery alert is converted into a case; triage rules, duplicate alerts, thresholds and review procedures influence that conversion.\nIllustrative closed-case outcome\nCount\nShare of closed cases\nNo Further Action (NFA)\n277\n90.8%\nSAR filed / escalated\n28\n9.2%\nTotal closed cases\n305\n100%\nAnalyst interpretation\nA rising alert count does not automatically mean financial crime has increased. Changes can reflect new scenarios, threshold\ntuning, seasonality, data quality or customer activity. Monitor alert-to-case conversion, investigation time, outcome distribution,\nrepeat alerts and quality-review findings together.\nIllustrative alert themes\nAlert theme\nShare of alerts\nPossible investigation question\nHigh-risk country exposure\n28%\nIs the country exposure justified by the customer’s business and counterparties?\nLarge amount\n24%\nIs the value consistent with expected turnover and historical behaviour?\nPotential structuring\n18%\nAre multiple transactions arranged to avoid controls or thresholds?\nUnusual pattern\n15%\nWhat changed from the customer’s normal activity?\nRapid movement / other\n15%\nDo funds move quickly through related parties without a clear rationale?\n',
 'FINANCIAL INTELLIGENCE | TRANSACTION MONITORING\nCONFIDENTIAL \x7f TRAINING EXAMPLE\nIllustrative synthetic data — not a real customer or bank investigation\nPage 4 of 5\n5. Transaction analysis: countries, amounts and currencies\nCountry exposure should be assessed using the full payment chain, not only the customer’s location. Originator and beneficiary\ncountry fields may reflect different parties in the payment message; intermediary banks and related entities can add further context.\nMeasure\nIllustrative value\nHow to use it\nTransactions reviewed\n18\nCheck whether all transactions are in scope and deduplicated.\nGross transaction value\nUSD 1.59m equivalent\nConfirm FX rates, value dates and whether reversals are included.\nLargest transaction\nUSD 250,000\nCompare with expected activity and documented business purpose.\nCountries shown\nUS, UK, China, UAE, India, Hong\nKong, Singapore\nValidate country fields and identify intermediaries / beneficial parties.\nInterpretation guardrail: a country or a large amount alone is not evidence of illicit activity. Consider customer profile, transaction\npurpose, counterparties, expected behaviour, source of funds, supporting documentation and applicable risk methodology.\n',
 'FINANCIAL INTELLIGENCE | TRANSACTION MONITORING\nCONFIDENTIAL \x7f TRAINING EXAMPLE\nIllustrative synthetic data — not a real customer or bank investigation\nPage 5 of 5\n6. Example alert case: investigation summary\nCase ID: C-2024-0158 | Alert types: High-risk country exposure + large amount | Status: Escalated for suspicious activity reporting\n(illustrative)\nField\nCase record\nField\nCase record\nCustomer ID\nCUST-987654\nCustomer type\nCorporate\nIndustry\nTrading\nCase opened\n15 Feb 2024\nCase closed\n22 Feb 2024\nInvestigation time\n5 days (working-time convention may vary)\nTransactions\nreviewed\n18\nRelated entities\n2 counterparties / entities\nTotal reviewed value\nUSD 1.59m equivalent\nDisposition\nSAR filed / escalated (example)\nIllustrative transaction network\nDate\nOriginator country\nBeneficiary country\nAmount (USD)\nCurrency\n12 Feb 2024\nUnited States\nUnited Arab Emirates\n250,000\nUSD\n13 Feb 2024\nUnited Arab Emirates\nHong Kong\n180,000\nUSD\n14 Feb 2024\nUnited States\nHong Kong\n95,000\nUSD\nInvestigation summary\nThe illustrative corporate customer initiated multiple high-value cross-border transfers involving the United States, the United Arab\nEmirates and Hong Kong over a short period. The pattern was flagged because the value and jurisdictional routing required review\nagainst the customer’s stated trading activity and expected payment profile. The investigator should validate invoices and contracts,\nconfirm the economic purpose and counterparties, assess source of funds, review related accounts and intermediaries, and\ndocument any inconsistencies. In this synthetic example, unresolved concerns led to escalation for suspicious activity reporting.\nKey conclusion: an alert is a starting point, not a finding. A defensible case summary connects the trigger, transaction facts, customer\ncontext, evidence reviewed, alternative explanations and reasoned disposition. Never infer criminality from geography or transaction\nvalue alone.\nTraining note: all IDs, dates, values, volumes and outcomes in this report are fictional and internally illustrative. They must not be used as real financial-crime\nstatistics, policy guidance or a live investigation record.\n']

In [18]:
 # Another way to do append  more details in dictionary format

page_records = []

for page_index, page in enumerate(reader.pages):
    page_number = page_index + 1
    extracted_text = page.extract_text() or ""
    words = extracted_text.split()
    page_records.append({
        "document_id" : document_id,
        "source_file" : PDF_PATH.name,
        "page_number" : page_number,
        "text" : extracted_text,
        "character_count" : len(extracted_text),
        "extraction_status" : "text_extracted" if words else " no selectable test",
    })

In [19]:
pages_df = pd.DataFrame(page_records)

In [20]:
pages_df

,document_id,source_file,page_number,text,character_count,extraction_status
0,PDF-16B4413CEE36,Chapter 57 - Alert_Case_Summary.pdf,1,Illustrative synthetic data — not a real custo...,1592,text_extracted
1,PDF-16B4413CEE36,Chapter 57 - Alert_Case_Summary.pdf,2,FINANCIAL INTELLIGENCE | TRANSACTION MONITORIN...,1821,text_extracted
2,PDF-16B4413CEE36,Chapter 57 - Alert_Case_Summary.pdf,3,FINANCIAL INTELLIGENCE | TRANSACTION MONITORIN...,1485,text_extracted
3,PDF-16B4413CEE36,Chapter 57 - Alert_Case_Summary.pdf,4,FINANCIAL INTELLIGENCE | TRANSACTION MONITORIN...,1213,text_extracted
4,PDF-16B4413CEE36,Chapter 57 - Alert_Case_Summary.pdf,5,FINANCIAL INTELLIGENCE | TRANSACTION MONITORIN...,2159,text_extracted

 # 6 . What exactly is a chunk

A chunk is a smaller text segment cut from a page's extracted text. In this chapter we count whitespace-separated words, rather than model tokens, because it makes the algorithm easy to inspect.

This first implementation intentionally does not allow a chunk to cross a page boundary. That makes page citations straightforward. Later systems can use larger document-level or section-aware chunks when appropriate.

Field	Meaning

document_id	= ID derived from the PDF's SHA-256 hash

source_file	= Original PDF filename

page_number	= One-based page number in the PDF

chunk_id = 	Unique ID for one chunk

chunk_index = 	One-based order within that page

word_start =	Zero-based position of the first word within the page text

word_end_exclusive	= Position just after the last word within the page text

word_count =	Number of words in this chunk

text =	Text passed to a future embedding/retrieval step

# 7. Implement a word-based chunker

The chunker uses a sliding window. For example, chunk_size=120 and overlap=20 means a chunk contains up to 120 words, and the next chunk starts 100 words later, repeating 20 words from the previous chunk.
The overlap is useful because a sentence or rule can straddle a chunk boundary. Too much overlap, however, creates extra duplicate text.

In [22]:
page_records

[{'document_id': 'PDF-16B4413CEE36',
  'source_file': 'Chapter 57 - Alert_Case_Summary.pdf',
  'page_number': 1,
  'text': 'Illustrative synthetic data — not a real customer or bank investigation\nPage 1 of 5\nTRANSACTION MONITORING\nALERT CASE SUMMARY\nA practical introduction to machine learning, alerts, cases and cross-border transaction analysis\n1. What is Machine Learning (ML)?\nMachine Learning is a branch of artificial intelligence in which a system learns patterns from data to make predictions, rank risks or\nidentify unusual behaviour. Instead of relying only on manually written rules, an ML model can learn what typical activity looks like\nfrom historical examples and flag transactions that differ from expected patterns.\nML concept\nMeaning in transaction monitoring\nFeatures\nInputs such as amount, currency, country, customer type, transaction frequency and prior behaviour.\nModel / score\nA model estimates risk or unusualness; a high score is a signal to review, not proof of wrongdoing.\nAlert\nA rule or model output that highlights activity for review by an analyst.\nHuman investigation\nAn investigator checks context, documents, counterparties and explanations before deciding the outcome.\nImportant: ML does not decide that a customer committed a crime. It supports prioritisation. Analysts must validate the evidence,\nconsider legitimate explanations and follow internal policy.\n2. Alert vs. case — what is the difference?\nAlert: a signal raised by a monitoring rule or model because a transaction or pattern meets risk criteria. Case: an investigation\nrecord that groups one or more related alerts, transactions, customers and supporting evidence so an analyst can assess the\nactivity as a whole.\n',
  'character_count': 1592,
  'extraction_status': 'text_extracted'},
 {'document_id': 'PDF-16B4413CEE36',
  'source_file': 'Chapter 57 - Alert_Case_Summary.pdf',
  'page_number': 2,
  'text': 'FINANCIAL INTELLIGENCE | TRANSACTION MONITORING\nCONFIDENTIAL \x7f TRAINING EXAMPLE\nIllustrative synthetic data — not a real customer or bank investigation\nPage 2 of 5\n3. Case scope and portfolio snapshot\nThis report uses a fictional three-month portfolio (1 January–31 March 2024) and one illustrative cross-border case. All names,\namounts and metrics are synthetic and provided only for learning how to summarise an alert investigation.\nMetric\nIllustrative value\nWhat it means\nAlerts generated\n1,245\nSignals raised by monitoring controls\nCases created\n320\nInvestigation records opened\nCases closed\n305\nCases with a recorded disposition\nSuspicious Activity Reports (SARs)\n28\nCases escalated for suspicious activity reporting\nNo Further Action (NFA)\n277\nCases closed without further escalation in this example\nAverage investigation time\n4.2 days\nIllustrative average from opening to closure\nTransactions in example case\n18\nTransactions linked to the selected case review\nCustomers / entities linked\n3\nOne customer and two related counterparties/entities\nHow to read the numbers\nAlerts and cases are not interchangeable: multiple alerts can be grouped into one case, and not every alert becomes a case. SAR\nand NFA are example dispositions and must be applied according to jurisdictional requirements and internal procedures. The\nsample totals are illustrative, not operational benchmarks.\nCase definition checklist\nCase element\nWhat should be recorded\nIdentity\nCase ID, customer ID, customer type, industry, account / entity references\nActivity\nTransaction count, total value, currencies, dates, originator and beneficiary countries\nRisk indicators\nAlert typology, model/rule reason, unusual behaviour, relevant thresholds\nEvidence and decision\nDocuments checked, explanation sought, findings, reviewer and final disposition\n',
  'character_count': 1821,
  'extraction_status': 'text_extracted'},
 {'document_id': 'PDF-16B4413CEE36',
  'source_file': 'Chapter 57 - Alert_Case_Summary.pdf',
  'page_number': 3,
  'text': 'FINANCIAL INTELLIGENCE | TRANSACTION MONITORING\nCONFIDENTIAL \x7f TRAINING EXAMPLE\nIllustrative synthetic data — not a real customer or bank investigation\nPage 3 of 5\n4. Alert and case trends\nThe chart compares alerts generated with cases created across the illustrative reporting period. The gap is expected because not\nevery alert is converted into a case; triage rules, duplicate alerts, thresholds and review procedures influence that conversion.\nIllustrative closed-case outcome\nCount\nShare of closed cases\nNo Further Action (NFA)\n277\n90.8%\nSAR filed / escalated\n28\n9.2%\nTotal closed cases\n305\n100%\nAnalyst interpretation\nA rising alert count does not automatically mean financial crime has increased. Changes can reflect new scenarios, threshold\ntuning, seasonality, data quality or customer activity. Monitor alert-to-case conversion, investigation time, outcome distribution,\nrepeat alerts and quality-review findings together.\nIllustrative alert themes\nAlert theme\nShare of alerts\nPossible investigation question\nHigh-risk country exposure\n28%\nIs the country exposure justified by the customer’s business and counterparties?\nLarge amount\n24%\nIs the value consistent with expected turnover and historical behaviour?\nPotential structuring\n18%\nAre multiple transactions arranged to avoid controls or thresholds?\nUnusual pattern\n15%\nWhat changed from the customer’s normal activity?\nRapid movement / other\n15%\nDo funds move quickly through related parties without a clear rationale?\n',
  'character_count': 1485,
  'extraction_status': 'text_extracted'},
 {'document_id': 'PDF-16B4413CEE36',
  'source_file': 'Chapter 57 - Alert_Case_Summary.pdf',
  'page_number': 4,
  'text': 'FINANCIAL INTELLIGENCE | TRANSACTION MONITORING\nCONFIDENTIAL \x7f TRAINING EXAMPLE\nIllustrative synthetic data — not a real customer or bank investigation\nPage 4 of 5\n5. Transaction analysis: countries, amounts and currencies\nCountry exposure should be assessed using the full payment chain, not only the customer’s location. Originator and beneficiary\ncountry fields may reflect different parties in the payment message; intermediary banks and related entities can add further context.\nMeasure\nIllustrative value\nHow to use it\nTransactions reviewed\n18\nCheck whether all transactions are in scope and deduplicated.\nGross transaction value\nUSD 1.59m equivalent\nConfirm FX rates, value dates and whether reversals are included.\nLargest transaction\nUSD 250,000\nCompare with expected activity and documented business purpose.\nCountries shown\nUS, UK, China, UAE, India, Hong\nKong, Singapore\nValidate country fields and identify intermediaries / beneficial parties.\nInterpretation guardrail: a country or a large amount alone is not evidence of illicit activity. Consider customer profile, transaction\npurpose, counterparties, expected behaviour, source of funds, supporting documentation and applicable risk methodology.\n',
  'character_count': 1213,
  'extraction_status': 'text_extracted'},
 {'document_id': 'PDF-16B4413CEE36',
  'source_file': 'Chapter 57 - Alert_Case_Summary.pdf',
  'page_number': 5,
  'text': 'FINANCIAL INTELLIGENCE | TRANSACTION MONITORING\nCONFIDENTIAL \x7f TRAINING EXAMPLE\nIllustrative synthetic data — not a real customer or bank investigation\nPage 5 of 5\n6. Example alert case: investigation summary\nCase ID: C-2024-0158 | Alert types: High-risk country exposure + large amount | Status: Escalated for suspicious activity reporting\n(illustrative)\nField\nCase record\nField\nCase record\nCustomer ID\nCUST-987654\nCustomer type\nCorporate\nIndustry\nTrading\nCase opened\n15 Feb 2024\nCase closed\n22 Feb 2024\nInvestigation time\n5 days (working-time convention may vary)\nTransactions\nreviewed\n18\nRelated entities\n2 counterparties / entities\nTotal reviewed value\nUSD 1.59m equivalent\nDisposition\nSAR filed / escalated (example)\nIllustrative transaction network\nDate\nOriginator country\nBeneficiary country\nAmount (USD)\nCurrency\n12 Feb 2024\nUnited States\nUnited Arab Emirates\n250,000\nUSD\n13 Feb 2024\nUnited Arab Emirates\nHong Kong\n180,000\nUSD\n14 Feb 2024\nUnited States\nHong Kong\n95,000\nUSD\nInvestigation summary\nThe illustrative corporate customer initiated multiple high-value cross-border transfers involving the United States, the United Arab\nEmirates and Hong Kong over a short period. The pattern was flagged because the value and jurisdictional routing required review\nagainst the customer’s stated trading activity and expected payment profile. The investigator should validate invoices and contracts,\nconfirm the economic purpose and counterparties, assess source of funds, review related accounts and intermediaries, and\ndocument any inconsistencies. In this synthetic example, unresolved concerns led to escalation for suspicious activity reporting.\nKey conclusion: an alert is a starting point, not a finding. A defensible case summary connects the trigger, transaction facts, customer\ncontext, evidence reviewed, alternative explanations and reasoned disposition. Never infer criminality from geography or transaction\nvalue alone.\nTraining note: all IDs, dates, values, volumes and outcomes in this report are fictional and internally illustrative. They must not be used as real financial-crime\nstatistics, policy guidance or a live investigation record.\n',
  'character_count': 2159,
  'extraction_status': 'text_extracted'}]

In [23]:
page_records

[{'document_id': 'PDF-16B4413CEE36',
  'source_file': 'Chapter 57 - Alert_Case_Summary.pdf',
  'page_number': 1,
  'text': 'Illustrative synthetic data — not a real customer or bank investigation\nPage 1 of 5\nTRANSACTION MONITORING\nALERT CASE SUMMARY\nA practical introduction to machine learning, alerts, cases and cross-border transaction analysis\n1. What is Machine Learning (ML)?\nMachine Learning is a branch of artificial intelligence in which a system learns patterns from data to make predictions, rank risks or\nidentify unusual behaviour. Instead of relying only on manually written rules, an ML model can learn what typical activity looks like\nfrom historical examples and flag transactions that differ from expected patterns.\nML concept\nMeaning in transaction monitoring\nFeatures\nInputs such as amount, currency, country, customer type, transaction frequency and prior behaviour.\nModel / score\nA model estimates risk or unusualness; a high score is a signal to review, not proof of wrongdoing.\nAlert\nA rule or model output that highlights activity for review by an analyst.\nHuman investigation\nAn investigator checks context, documents, counterparties and explanations before deciding the outcome.\nImportant: ML does not decide that a customer committed a crime. It supports prioritisation. Analysts must validate the evidence,\nconsider legitimate explanations and follow internal policy.\n2. Alert vs. case — what is the difference?\nAlert: a signal raised by a monitoring rule or model because a transaction or pattern meets risk criteria. Case: an investigation\nrecord that groups one or more related alerts, transactions, customers and supporting evidence so an analyst can assess the\nactivity as a whole.\n',
  'character_count': 1592,
  'extraction_status': 'text_extracted'},
 {'document_id': 'PDF-16B4413CEE36',
  'source_file': 'Chapter 57 - Alert_Case_Summary.pdf',
  'page_number': 2,
  'text': 'FINANCIAL INTELLIGENCE | TRANSACTION MONITORING\nCONFIDENTIAL \x7f TRAINING EXAMPLE\nIllustrative synthetic data — not a real customer or bank investigation\nPage 2 of 5\n3. Case scope and portfolio snapshot\nThis report uses a fictional three-month portfolio (1 January–31 March 2024) and one illustrative cross-border case. All names,\namounts and metrics are synthetic and provided only for learning how to summarise an alert investigation.\nMetric\nIllustrative value\nWhat it means\nAlerts generated\n1,245\nSignals raised by monitoring controls\nCases created\n320\nInvestigation records opened\nCases closed\n305\nCases with a recorded disposition\nSuspicious Activity Reports (SARs)\n28\nCases escalated for suspicious activity reporting\nNo Further Action (NFA)\n277\nCases closed without further escalation in this example\nAverage investigation time\n4.2 days\nIllustrative average from opening to closure\nTransactions in example case\n18\nTransactions linked to the selected case review\nCustomers / entities linked\n3\nOne customer and two related counterparties/entities\nHow to read the numbers\nAlerts and cases are not interchangeable: multiple alerts can be grouped into one case, and not every alert becomes a case. SAR\nand NFA are example dispositions and must be applied according to jurisdictional requirements and internal procedures. The\nsample totals are illustrative, not operational benchmarks.\nCase definition checklist\nCase element\nWhat should be recorded\nIdentity\nCase ID, customer ID, customer type, industry, account / entity references\nActivity\nTransaction count, total value, currencies, dates, originator and beneficiary countries\nRisk indicators\nAlert typology, model/rule reason, unusual behaviour, relevant thresholds\nEvidence and decision\nDocuments checked, explanation sought, findings, reviewer and final disposition\n',
  'character_count': 1821,
  'extraction_status': 'text_extracted'},
 {'document_id': 'PDF-16B4413CEE36',
  'source_file': 'Chapter 57 - Alert_Case_Summary.pdf',
  'page_number': 3,
  'text': 'FINANCIAL INTELLIGENCE | TRANSACTION MONITORING\nCONFIDENTIAL \x7f TRAINING EXAMPLE\nIllustrative synthetic data — not a real customer or bank investigation\nPage 3 of 5\n4. Alert and case trends\nThe chart compares alerts generated with cases created across the illustrative reporting period. The gap is expected because not\nevery alert is converted into a case; triage rules, duplicate alerts, thresholds and review procedures influence that conversion.\nIllustrative closed-case outcome\nCount\nShare of closed cases\nNo Further Action (NFA)\n277\n90.8%\nSAR filed / escalated\n28\n9.2%\nTotal closed cases\n305\n100%\nAnalyst interpretation\nA rising alert count does not automatically mean financial crime has increased. Changes can reflect new scenarios, threshold\ntuning, seasonality, data quality or customer activity. Monitor alert-to-case conversion, investigation time, outcome distribution,\nrepeat alerts and quality-review findings together.\nIllustrative alert themes\nAlert theme\nShare of alerts\nPossible investigation question\nHigh-risk country exposure\n28%\nIs the country exposure justified by the customer’s business and counterparties?\nLarge amount\n24%\nIs the value consistent with expected turnover and historical behaviour?\nPotential structuring\n18%\nAre multiple transactions arranged to avoid controls or thresholds?\nUnusual pattern\n15%\nWhat changed from the customer’s normal activity?\nRapid movement / other\n15%\nDo funds move quickly through related parties without a clear rationale?\n',
  'character_count': 1485,
  'extraction_status': 'text_extracted'},
 {'document_id': 'PDF-16B4413CEE36',
  'source_file': 'Chapter 57 - Alert_Case_Summary.pdf',
  'page_number': 4,
  'text': 'FINANCIAL INTELLIGENCE | TRANSACTION MONITORING\nCONFIDENTIAL \x7f TRAINING EXAMPLE\nIllustrative synthetic data — not a real customer or bank investigation\nPage 4 of 5\n5. Transaction analysis: countries, amounts and currencies\nCountry exposure should be assessed using the full payment chain, not only the customer’s location. Originator and beneficiary\ncountry fields may reflect different parties in the payment message; intermediary banks and related entities can add further context.\nMeasure\nIllustrative value\nHow to use it\nTransactions reviewed\n18\nCheck whether all transactions are in scope and deduplicated.\nGross transaction value\nUSD 1.59m equivalent\nConfirm FX rates, value dates and whether reversals are included.\nLargest transaction\nUSD 250,000\nCompare with expected activity and documented business purpose.\nCountries shown\nUS, UK, China, UAE, India, Hong\nKong, Singapore\nValidate country fields and identify intermediaries / beneficial parties.\nInterpretation guardrail: a country or a large amount alone is not evidence of illicit activity. Consider customer profile, transaction\npurpose, counterparties, expected behaviour, source of funds, supporting documentation and applicable risk methodology.\n',
  'character_count': 1213,
  'extraction_status': 'text_extracted'},
 {'document_id': 'PDF-16B4413CEE36',
  'source_file': 'Chapter 57 - Alert_Case_Summary.pdf',
  'page_number': 5,
  'text': 'FINANCIAL INTELLIGENCE | TRANSACTION MONITORING\nCONFIDENTIAL \x7f TRAINING EXAMPLE\nIllustrative synthetic data — not a real customer or bank investigation\nPage 5 of 5\n6. Example alert case: investigation summary\nCase ID: C-2024-0158 | Alert types: High-risk country exposure + large amount | Status: Escalated for suspicious activity reporting\n(illustrative)\nField\nCase record\nField\nCase record\nCustomer ID\nCUST-987654\nCustomer type\nCorporate\nIndustry\nTrading\nCase opened\n15 Feb 2024\nCase closed\n22 Feb 2024\nInvestigation time\n5 days (working-time convention may vary)\nTransactions\nreviewed\n18\nRelated entities\n2 counterparties / entities\nTotal reviewed value\nUSD 1.59m equivalent\nDisposition\nSAR filed / escalated (example)\nIllustrative transaction network\nDate\nOriginator country\nBeneficiary country\nAmount (USD)\nCurrency\n12 Feb 2024\nUnited States\nUnited Arab Emirates\n250,000\nUSD\n13 Feb 2024\nUnited Arab Emirates\nHong Kong\n180,000\nUSD\n14 Feb 2024\nUnited States\nHong Kong\n95,000\nUSD\nInvestigation summary\nThe illustrative corporate customer initiated multiple high-value cross-border transfers involving the United States, the United Arab\nEmirates and Hong Kong over a short period. The pattern was flagged because the value and jurisdictional routing required review\nagainst the customer’s stated trading activity and expected payment profile. The investigator should validate invoices and contracts,\nconfirm the economic purpose and counterparties, assess source of funds, review related accounts and intermediaries, and\ndocument any inconsistencies. In this synthetic example, unresolved concerns led to escalation for suspicious activity reporting.\nKey conclusion: an alert is a starting point, not a finding. A defensible case summary connects the trigger, transaction facts, customer\ncontext, evidence reviewed, alternative explanations and reasoned disposition. Never infer criminality from geography or transaction\nvalue alone.\nTraining note: all IDs, dates, values, volumes and outcomes in this report are fictional and internally illustrative. They must not be used as real financial-crime\nstatistics, policy guidance or a live investigation record.\n',
  'character_count': 2159,
  'extraction_status': 'text_extracted'}]

# 9. Implement a word-based chunker

In [ ]:
def chunk_page_text(page_records, chunk_size=120, overlap=20):
    # 1. Type and value validations
    if not isinstance(page_records, list):
        raise TypeError("page_records must be a list of page dictionaries")
    if not isinstance(chunk_size, int) or chunk_size <= 0:
        raise ValueError("chunk_size must be a positive integer")
    if not isinstance(overlap, int) or overlap < 0:
        raise ValueError("overlap must be a non-negative integer")
    if overlap >= chunk_size:
        raise ValueError("overlap must be smaller than chunk_size")

    all_chunks = []
    step = chunk_size - overlap

    for page_record in page_records:
        if not isinstance(page_record, dict):
            raise TypeError("Each element in page_records must be a dictionary")

        text = page_record.get("text", "")
        if not isinstance(text, str):
            raise TypeError("page_record['text'] must be a string")

        words = text.split()
        if not words:
            continue

        start = 0
        chunk_index = 1
        page_number = int(page_record["page_number"])

        while start < len(words):
            end = min(start + chunk_size, len(words))
            all_chunks.append({
                "document_id": page_record["document_id"],
                "source_file": page_record["source_file"],
                "page_number": page_number,
                "chunk_id": f"{page_record['document_id']}-P{page_number:03d}-C{chunk_index:03d}",
                "chunk_index": chunk_index,
                "word_start": start,
                "word_count": end - start,
                "text": " ".join(words[start:end]),
            })

            if end == len(words):
                break

            start += step
            chunk_index += 1

    return all_chunks

In [39]:
chunks = chunk_page_text(page_records, chunk_size=120, overlap=20)
print(f"Total chunks created: {len(chunks)}")

Total chunks created: 13

# 14. Try a keyword lookup over the chunks

In [40]:
def keyword_search_chunks(query, chunks, max_results =5):
    if not isinstance(query, str):
        raise ValueError("query must be a non empty string")
    if not isinstance(max_results, int) or max_results < 1:
        raise ValueError("max results mist be a positive integer")

    query_lower = query.casefold()

    results = []

    for record in chunks:
        if query_lower in record["text"].casefold():
            results.append({
                "source_file": record["source_file"],
                "page_number": record["page_number"],
                "chunk_id": record["chunk_id"],
                "text": record["text"],
            })
            if len(results) >= max_results:
                break
    return results

search_results = keyword_search_chunks("How to read the numbers", chunks, max_results=5)
pd.DataFrame(search_results)

,source_file,page_number,chunk_id,text
0,Chapter 57 - Alert_Case_Summary.pdf,2,PDF-16B4413CEE36-P002-C002,suspicious activity reporting No Further Actio...

In [41]:
with pd.option_context("display.max_colwidth", None):
    display(pd.DataFrame(search_results))

,source_file,page_number,chunk_id,text
0,Chapter 57 - Alert_Case_Summary.pdf,2,PDF-16B4413CEE36-P002-C002,"suspicious activity reporting No Further Action (NFA) 277 Cases closed without further escalation in this example Average investigation time 4.2 days Illustrative average from opening to closure Transactions in example case 18 Transactions linked to the selected case review Customers / entities linked 3 One customer and two related counterparties/entities How to read the numbers Alerts and cases are not interchangeable: multiple alerts can be grouped into one case, and not every alert becomes a case. SAR and NFA are example dispositions and must be applied according to jurisdictional requirements and internal procedures. The sample totals are illustrative, not operational benchmarks. Case definition checklist Case element What should be recorded Identity Case ID, customer ID, customer type, industry, account /"